import { GoogleGenAI, GenerateContentResponse, Type } from '@google/genai';
import { PaymentDetails, PaymentType } from '../types';

/**
 * Initializes the GoogleGenAI client.
 * Assumes process.env.API_KEY is available in the environment.
 * A new instance is created for each call to ensure the latest API key is used,
 * as per best practices for Veo/Imagen models, which can be extended to all models for consistency.
 */
const getGeminiClient = () => {
  if (!process.env.API_KEY) {
    console.error('API_KEY is not defined. Gemini API calls will fail.');
    // For local development or testing without an actual API key, you might return a mock client
    // or throw an error. For this exercise, we assume it's set as per the prompt.
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY || 'YOUR_MOCK_API_KEY_HERE' });
};

/**
 * Generates a WhatsApp message draft for payment confirmation using the Gemini API.
 * @param details - The payment details provided by the user.
 * @returns A promise that resolves to the generated message string.
 */
export const generatePaymentConfirmationMessage = async (
  details: PaymentDetails,
): Promise<string> => {
  try {
    const ai = getGeminiClient();
    const model = 'gemini-2.5-flash'; // Using gemini-2.5-flash for basic text generation

    const prompt = `Por favor, genera un mensaje conciso y amigable para WhatsApp confirmando un pago.
    Incluye los siguientes detalles:
    - Tipo de pago: ${details.type === PaymentType.WORKSHOP ? 'Taller de Primeros Auxilios' : 'Libro'}
    - Título del artículo/taller: ${details.itemTitle || 'No especificado'}
    - Nombre completo del pagador: ${details.fullName}
    - Identificación del pagador: ${details.identification}
    - País de origen (si aplica): ${details.country || 'No especificado'}

    También, añade una instrucción amigable al final para que la persona adjunte la captura de pantalla del pago.
    El mensaje debe ser directo y fácil de entender.`;

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: model,
      contents: [{ parts: [{ text: prompt }] }],
      config: {
        temperature: 0.7, // A bit creative but not too wild
        maxOutputTokens: 200, // Keep the message concise
      },
    });

    const generatedText = response.text;
    if (!generatedText) {
      throw new Error('No text was generated by the Gemini API.');
    }
    return generatedText.trim();
  } catch (error) {
    console.error('Error calling Gemini API for payment message generation:', error);
    // Fallback message in case of API error
    return `Hola, he recibido tu solicitud de confirmación de pago.
    Tipo de pago: ${details.type === PaymentType.WORKSHOP ? 'Taller de Primeros Auxilios' : 'Libro'} (${details.itemTitle || 'No especificado'})
    Nombre: ${details.fullName}
    Identificación: ${details.identification}
    País: ${details.country || 'No especificado'}
    Por favor, adjunta la captura de pantalla del pago en este chat para verificarlo. ¡Gracias!`;
  }
};